### ISSUE TITLE
Log wird zugespamt und lua Errors

### ISSUE THREAD

**Issue by luk1TAH** [modelleicher/FS19_realManualTransmission#1]
Log wird zugespamt mit "is not low braking" bzw. "is low braking"
Nach wenigen Minuten dann lua Errors. Es wurden keine zusätzlichen Mods verwendet, der Fehler ist bei der Valtra A Serie und bei der John Deere M Serie aufgetreten.
[log.txt](https://github.com/modelleicher/FS19_realManualTransmission/files/2825899/log.txt)

**Comment by modelleicher** [comment]
Sollte in der aktuellen Version (V0.4.0.1) gefixt sein :)
