### ISSUE TITLE
workRPM

### ISSUE THREAD

**Issue by ivanlii** [modelleicher/FS19_realManualTransmission#10]
Hi, could you add power consumer, is not too immersive right now.
Thanks!

**Comment by modelleicher** [comment]
Hi, what is not too immersive? If you work with an implement you need to set the RPM with handthrottle just like IRL.. ;) Tractors don't auto-rev up as soon as you turn the PTO on

**Comment by ivanlii** [comment]
Well if the handthrottle is just cosmetics now for implements, you could add a feature that they dont start until a minRpm (rated, max) is reached.

**Comment by modelleicher** [comment]
Well, handthrottle is not just cosmetics. But IRL you can engage PTO at low RPM as well no problem. (unless its a baler maybe) but most implements barely draw any power at "idle" e.g. when they do not do any work.

Right now FS has a very weak calculation for power usage of PTO implements.. Without fixing that, there is no point in adding some weird fake stall stuffs. 
If you want to play realistically just play as you would IRL.. if you engage the PTO to something that requires a lot of power on startup just raise the RPMs a bit and then set the RPM to the desired working RPM for that implement.
Depending on working speed and what you want to achieve rpm varies a lot IRL.. There is no set value..
So I don't think it makes sense to fake that value :)

**Comment by ivanlii** [comment]
Ok, thank you, i understand your opinion. Keep the good work!
