### ISSUE TITLE
Im RMT-Menü kann ich nix Einstellen

### ISSUE THREAD

**Issue by Steyr4ever** [modelleicher/FS19_realManualTransmission#102]
Hi,
ich kann im RMT-Menü nichts einstellen, aber ansonsten funktioniert alles.
Kann mir wer helfen?

**Comment by modelleicher** [comment]
Hi, das klassische Problem der Doppelbelegungen.. z.b. durch Courseplay

**Comment by modelleicher** [comment]
Durch das neue Menü-System sollte es keine Doppelbelegungs-Probleme mehr geben. #Closed
