### ISSUE TITLE
RMT shifting axis for fps transmissions v 0.6.1.3

### ISSUE THREAD

**Issue by CityFarmerDE** [modelleicher/FS19_realManualTransmission#103]
Binding the shifting axis to an input device blocks the direct gear selection. Maybe add a menu or button to turn the shifting axis on/off. 

Shifting with axis works.

**Comment by modelleicher** [comment]
Hmm didn't think of that but yeah makes sense since the axis is constantly active.. Yeah I guess I have to add a menu option for that for now. I have to redo the menu at some point

**Comment by astro80** [comment]
it`s would be a very nice addition, i love this new way to use rmt and fps transmission. thank you very much!

**Comment by astro80** [comment]
It's possible to have the N position at the end of the axis course?

**Comment by modelleicher** [comment]
Currently there is no working "n" position for the gears, I'm not quite sure how I will solve this

**Comment by astro80** [comment]
Ok thank you, it's a very good addition in any case.

**Comment by CityFarmerDE** [comment]
Works for me now. Thanks.
