### ISSUE TITLE
Kein Loadsound im Leerlauf / Stand

### ISSUE THREAD

**Issue by Kobes94** [modelleicher/FS19_realManualTransmission#109]
Hallo

Keine Ahnung ob du an diesem Mod noch arbeitest.
Aber wenn Geräte (Mähwerke, etc.) eingeschaltet werden, erhöht sich die Motordrehzahl nicht.
Sobald ich RMT mit der Tastenkombi aussschalte, geht die Drehzahl hoch.

Grüsse
Kobes

**Comment by modelleicher** [comment]
Moin, ne LS19 ist Geschichte ;) 

Und das was du beschreibst ist kein Fehler sondern ein Feature. In echt geht die Drehzahl auch nicht automatisch hoch sobald man ein Gerät einschaltet - dafür gibts das Handgas.

Die Drehzahl ist auch nicht gleich Loadsound ;) 

LG

**Comment by Kobes94** [comment]
Alles klar, danke. :)

Dann werd ich mal schauen, wie ich die Tastenkombi setze fürs Handgas.
