### ISSUE TITLE
Set default name for gears

### ISSUE THREAD

**Issue by yumi-modding** [modelleicher/FS19_realManualTransmission#11]
Hello modelleicher,
This is a really great project your starting here! It might makes me move to FS19.
Just a small addition after a very quick test: could you define default name for gears if none is set in the config (like 1, 2, 3...)
This way more configs could be imported directly from previous gearBoxAddon.
Also, don't hesitate to contact me if you need code snippet to load config for mods from xml external file.

**Comment by modelleicher** [comment]
Hello,
I tried to have as little optional parts as possible as I think it makes it easier for people to create their own configurations if most of the possible attributes are always there, but making it possible to use configs from GearboxAddon is a valid argument I guess :) I will add default naming in the next update ;)
