### ISSUE TITLE
Verwendung auf Server möglich?

### ISSUE THREAD

**Issue by punkyletszock** [modelleicher/FS19_realManualTransmission#13]
Hallo Modelleicher,

ist die Verwendung in diesem frühen Entwicklungsprozess auch für ein Dedicated Server vorgesehen?

Mit freundlichen Grüßen
David

**Comment by modelleicher** [comment]
Hallo,

Der Mod ist noch nicht Multiplayer-fähig. (Es sind weder Events noch Synchronisationen verbaut) 

LG
