### ISSUE TITLE
Verbesserungsvorschlag

### ISSUE THREAD

**Issue by Markus412** [modelleicher/FS19_realManualTransmission#14]
Hey, modelleicher ich find den Mod echt super und hab mir inzwischen für den Valtra A zwei Getriebegonfigs geschrieben, genauso wie für den Hürlimann H488. Mein Wunsch wäre noch ein Stufenloser Eintrag und die Möglichkeit die Wendeschaltung so zu "schreiben", dass sie nur per Kupplung zu schalten ist. Ansonsten echt ein super Mod und sehr übersichtlich in der XML echt super ;)

LG Markus

**Comment by modelleicher** [comment]
Hi,
Was meinst du mit Wendeschaltung die nur per Kupplung zu schalten ist? 

LG

**Comment by Markus412** [comment]
Hi, momentan ist es ja so, es gibt einmal die elektronische Wendeschaltung mit Vorwahl (Favorit 500 C) oder die ganz normale Wendeschaltung ohne Vorwahl. Bei mir ist es aber so, dass die normale Wendeschaltung ohne das ich die Kupplung trete die Fahrtrichtung ändert und in echt, zumindest bei den älteren Schleppern, die Kupplung getreten werden muss.

**Comment by modelleicher** [comment]
Hi,
Gibt es das, eine elektronische/elektrische Wendeschaltung die aber nur bei getretener Kupplung funktioniert?

LG

**Comment by BlackscreenHD** [comment]
Es gibt definitiv mechanische Wendeschaltungen, oder wie Fendt sie beim Farmer 300C nennt: Vollsynchron-Wechsel-Feinstufengetriebe/Wendegetriebe und mechanische V/R-Schaltung.
Dort hat man halt lenks neben dem Lenkrad einen Hebel zum Richtungswechsel, der nur bei getretener Kupplung bewegt werden (sollte :D )kann. 
Bei Case gibt es das Verfahren beispielsweise beim CX 90 auch.

**Comment by Anwalt80** [comment]
Ich kenne das auch so.  Man kann zB das Rückwärtsfahren schon am Kippschalter vorwählen (Pfeil im Display blinkt) und beim nächsten betätigen der Kupplung fährt der Schlepper dann Rückwärts.
