### ISSUE TITLE
'preselect' function / Wendegetriebe mit Vorwahlfunktion

### ISSUE THREAD

**Issue by DrewCZ** [modelleicher/FS19_realManualTransmission#15]
Hello modelleicher,
first many many thanks for your work. Without your mods I never play FS longer than few days. 

I have one challenge. In Wiki about Fendt Favorit 500 I was found that gearbox have 'preselect' function = 'Wendegetriebe mit Vorwahlfunktion'. 
It will be so nice, have chance to preselect gear and then using clutch to gear down.

Only idea... ;-)
Thank you and have nice days.
DrewCZ

**Comment by modelleicher** [comment]
Hello,
The preselect function is refering to the reverser and that is already implemented in RMT ;)

**Comment by DrewCZ** [comment]
Well, and it works on each type of gears?

**Comment by DrewCZ** [comment]
Ok, last question about Fendt. Will be possible block one gear for one rangeSet? Fend Favorit 500 have gear 6 blocked in 'Kriech' rangeset. 
Source: [Wiki](https://de.wikibooks.org/wiki/Traktorenlexikon:_Fendt_Favorit_510_C#Getriebe)

For exmaple
`<gear speed="50.0" name="6" blockedByRange="KR" />`
and then name of blocking range:
`<rangeSet2 powerShift="true" defaultRange="2" >
      <range ratio="0.5" name="KR" />`
What do you think about?
Dr.CZ

**Comment by modelleicher** [comment]
Hello,

It is possible to block certain gears in certain ranges. You can look at the basegameConfigs.xml for a full list of possible attributes and a short explanation.
It works like this:

`			<range ratio="0.5" name="KR" >
				<disableGears gears="6" disableType="lock" />
			</range>`

**Comment by DrewCZ** [comment]
Great, thank you, file 'basegameConfigs' helps well.
