### ISSUE TITLE
H-schaltung Gänge springen nicht in Neutral

### ISSUE THREAD

**Issue by D9005** [modelleicher/FS19_realManualTransmission#17]
Hallo Modelleicher, habe mir gestern Abend die neue Version des RMT's runtergeladen und mir ist aufgefallen, dass die Gänge bei der H-schaltung nicht wieder in Neutral springen sobald man den Schalthebel z.B. von Gang 1 in Neutral bewegt. Es bleibt Gang 1 angewählt. Habe nocht nicht geschaut ob es vielleicht einen Modkonflikt gibt.

MfG D9005

**Comment by modelleicher** [comment]
Sollte mit V 0.4.0.9 wieder gefixt sein :)

**Comment by D9005** [comment]
Perfekt, hat geklappt.
Vielen Dank! :)
