### ISSUE TITLE
Gang hoch runter schalten vertauscht

### ISSUE THREAD

**Issue by lukimaho** [modelleicher/FS19_realManualTransmission#18]
Hallo 
Mir ist heute beim Tastenbelegen aufgefallen, dass Gang hoch bzw Gang runter vertauscht ist, weil ich habe Gang hoch auf Numpad + und runter auf - doch im Traktor ist es genau umgekehrt. Wenn ich - drücke schaltet er hoch und wenn ich + drücke runter.

**Comment by modelleicher** [comment]
Hallo, danke wird in der nächsten Version gefixt :)

**Comment by Relu83** [comment]
Hi-m-geprüfte Übertragung ist in Ordnung
Ich habe es im Spiel und kann sogar Gutes tun
realistisch, wenn Sie für meine Spiele mit Respekt implementieren können


Relu
