### ISSUE TITLE
Reverser

### ISSUE THREAD

**Issue by jacob7557** [modelleicher/FS19_realManualTransmission#19]
Die Buchstaben für Vorwärts sind unterschiedlich
![fsScreen_2019_03_13_22_21_12](https://user-images.githubusercontent.com/48649892/54492442-fdc85580-48c6-11e9-8a2c-bb460dd36ae2.png)
![fsScreen_2019_03_13_22_21_09](https://user-images.githubusercontent.com/48649892/54492443-fdc85580-48c6-11e9-88f6-ad3937a2e7bc.png)

**Comment by modelleicher** [comment]
Danke :)

**Comment by modelleicher** [comment]
Finally fixed :D
