### ISSUE TITLE
RTM-Mod wird im Spiel nicht angezeigt

### ISSUE THREAD

**Issue by CoolpixHD** [modelleicher/FS19_realManualTransmission#21]
Hallo Sam
Erstmal vielen Dank, dass du dir die Mühe machst ein solches Script zu bauen. Respekt!
Ich weis nicht ob mir hier geholfen werden kann, aber ich beschreibe mal die Situation:
Ich habe deinen Mod heute heruntergeldaden und so wie du es in deinem YT-Video beschrieben hast in den Modordner gepack. Doch leider wird der Mod in der Modauswahl nicht angezeigt. Kann das evt. daran liegen, dass die RTM noch nicht für die Version 1.3.0.1 des Farming Simulators kompartibel ist oder was könnten noch Gründe sein?
Mfg Coolpix

**Comment by modelleicher** [comment]
Hallo,
RMT ist mit 1.3.0.1 kompatibel
