### ISSUE TITLE
Request to  Add Sounds to handbrake

### ISSUE THREAD

**Issue by Kehlun** [modelleicher/FS19_realManualTransmission#22]
Hello dear modelleiche
I would really love and like it if you could consider adding sounds to this mod.
its an amazing mod and I really enjoy it. 
ive added it to all my mods and some of the ingame vehicles that weren't done yet.
I play without my hud on so its more immersive however, I miss sounds like when I put the handbrake on I don't know if its set unless I stall it trying to drive away or pulling m hud up.

thank you very much for reading this and may it help you develop this amazing transmission mod in the game

a pleasure Kehlun

**Comment by modelleicher** [comment]
Hello,

I will add sounds to the mod in due time ;) But its not on top of the priority list right now.

**Comment by Kehlun** [comment]
hello Modelleicher

that is great to hear and I understand that its not a priority. plz keep up the good work. I really love and enjoy your work
