### ISSUE TITLE
Speedmatching

### ISSUE THREAD

**Issue by JohnDeere6920** [modelleicher/FS19_realManualTransmission#23]
Hallo Modelleicher. 
Erstmal vielen dank für den tollen mod. Ich habe mir das getriebe in einen 6M mod eingebaut. funktioniert auch soweit. Jetzt hätte ich nich gerne, das die lastschaltstufen sich der geschwindigkeit anpassen wenn man einen gang schaltet. Also z.B. von D-4 in E-2. Und das man Vorwärts und rückwärts ohne kupplung schalten kann. 

MfG 
John Deere 6920

**Comment by modelleicher** [comment]
Hallo,
Vorwärts-Rückwärts ohne Kupplung geht bereits.

Speedmatching steht noch auf der Liste unter anderem.. aber nicht ganz oben :D

**Comment by JohnDeere6920** [comment]
Hallo,
Das mit vorwärts-Rückwärts habe ich auch hinbekommen. Auf jeden fall schonmal vielen dank, das du dir überhaupt die mühe machst und die schaltung wieder ins leben gerufen hast. Ich war schon am Verzweifeln ohne Schaltung :D. Wird es irgendwann auch stufenlose getriebe geben oder ist das überhaupt nicht geplant?
Gruß

**Comment by modelleicher** [comment]
Nicht sicher wegen Stufenlos.. wenn dann müsste es ja schon realistisch aufgebaut sein ;)

**Comment by JohnDeere6920** [comment]
Okay. Trotzdem schonmal vielen dank :D

**Comment by modelleicher** [comment]
speedmatching für die Ranges gibt es seit der aktuellen Version V 0.5.1.2 ;)
