### ISSUE TITLE
Gruppenschaltung funktioniert nicht

### ISSUE THREAD

**Issue by huttndav** [modelleicher/FS19_realManualTransmission#24]
Hi Sam,
ich habe letztens den RMT Mod etwas eingestellt und getestet. Dort ist mir schon aufgefallen, dass irgendwas mit dem durchschalten der Gruppen nicht funktioniert, da ich aber noch keine Verwendung für den Mod hatte beschäftigte ich mich nicht weiterhin damit. Heute wollte ich das erste mal damit spielen, da fiel mir auf, dass es wieder nicht richtig ging mit dem durchschalten der Gruppen, also habe ich etwas rumprobiert. Das Ende vom Lied: Manchmal funktioneirt es und Manchmal nicht, und es funktioniert weder auf der Tastatur noch auf meinem G920.
Ich wäre sehr dankbar, wenn du mir weiterhelfen könntest.
Und trotz der unklarheit Danke für den tollen Mod!

Mfg Huttndav a.k.a. da Reidoiabauer

**Comment by modelleicher** [comment]
Hi,

Da hab ich jetzt so auf Anhieb auch keine Idee. Ich hab auch öfter Probleme mit den Gruppen, allerdings nur am Schalthebel, Tastatur funktioniert immer. Und ich hab die selben Probleme auch im LS17 mit Gearbox-Addon also war ich mir sicher dass es am Schalthebel liegt und nicht am Script.

Kann es sich eventuell um einen Tastenkonflikt handeln? Kannst du genauer beschreiben ob es irgend einer Logik folgt wann es geht und wann nicht? (z.b. nach dem aus/einsteigen in den Traktor geht es manchmal und manchmal nicht, oder ist es wirklich komplett zufällig?)

LG
