### ISSUE TITLE
Roll Wiederstand beim ausrollen ohne Gang

### ISSUE THREAD

**Issue by DonPaul75** [modelleicher/FS19_realManualTransmission#28]
Hi, Da ich bei deinen Youtube videos gehort hatte, das Du ewentuell eine  weitere entwicklung machen willst. Habe ich eine bemerkung. Beim Schalten ins neutral, rollen die vehicles ohne wiederstand weiter. Kann mann da etwas einstellen/einbauen das mann denn rollwiederstand simulieren kann, damit die vehicels beim ausrollen auf der ebener auch selber bischen abbremsen bis zum still stand. Koennte mann eventuell an Gesamt mass/gewicht einbinden damit leichtere verzeuge weiter rollen als die schweren. Sonst danke fur die jetzige arbeit, macht deutlich mehr spass als ohne.

**Comment by modelleicher** [comment]
Hi,
An sich sollte da Rollwiderstand da sein auch wenn der Gang draußen ist, allein schon von der LS Vehicle Physik.. Im Gegenteil ich musste ganz schön kämpfen dass die Kisten nicht sofort stehen bleiben :D 

Aber da muss ich noch mal testen, kann natürlich sein dass ich bei den vielen Versionen irgendwo irgendwas deaktiviert hab und es nicht bemerkt habe ;) 

LG
