### ISSUE TITLE
Funktioniert nicht mit dem  logitech shifter

### ISSUE THREAD

**Issue by Trabifahrer** [modelleicher/FS19_realManualTransmission#29]
im spiel werden die gäge mit h schaltung nicht geschalten obwohl bei der tastenbelegung alles erkannt wird.

**Comment by Black4Hawk76** [comment]
Moin Trabifahrer, ich nutze den Shifter vom G29 und bis auf den Rückwärtsgang, geht alles.
Ich musste hierfür nur die 2Belegung nutzen.
G Black
