### ISSUE TITLE
Multiplayer Mod unterstützung

### ISSUE THREAD

**Issue by SaveSpace93** [modelleicher/FS19_realManualTransmission#32]
Bitte ein Standart Getriebe für alle mod schlepper einbauen, z.b. wie das default aus dem Gearbox addon. Bitte möglichst schnell den Multiplayer in gang setzten, unser Team spielt so realistisch wie möglich, nur ein gearbox fehlt noch

**Comment by modelleicher** [comment]
Standard Getriebe wirds keins geben da halt ich nix von. Entweder realistisch oder gar nicht ;)
