### ISSUE TITLE
Bad synchronization on multiplayer

### ISSUE THREAD

**Issue by KreciKK** [modelleicher/FS19_realManualTransmission#35]
When someone join server while i'm in tractor, gearbox and clutch will lock and I need to sell vehicle. Next issue is when i drive tractor, and someone enter other tractor, i will change his gears, but my gearbox and clutch will lock. Please fix it if you can :)

**Comment by modelleicher** [comment]
The Issue that you can control other people's vehicles should be fixed with this version V 0.5.1.1
Please report back if the locking gearbox and clutch while joining still occurs, I changed something but I'm not sure if that was the issue.
