### ISSUE TITLE
Probleme mit AE und Controllern

### ISSUE THREAD

**Issue by RuppMartin001** [modelleicher/FS19_realManualTransmission#37]
Hallo modelleicher,

ich bekomme leider RMT V 0.5.1.1 nicht zum Laufen.

Ich habe mehrere Controller im Spiel LS19 im Einsatz:
- Lenkrad mit Pedalen: Logitech MOMO Force Feedback (Nur Gas und Bremspedal)
- Joystic: Microsoft Sidewinder Force Feedback 2
- Gangschaltung: Thrustmaster TH8A
- Zweites Pedalset: Fanatec Elite Pedals LC - CSL
- X-Box 360 Gamepad-Controler
- Contour Shuttlepro V2

1. Problem: Knöpfe werden von RMT nicht erkannt:
Den Reverser und die Umschalter der Rangesets 1 und 2 habe ich auf Knöpfe des Lenkrads gelegt. Leider kommt keine Reaktion, wenn ich die Knöpfe anklicke.
Der Reverser hat die gleiche Belegung, wie unter AE.
Dort sieht man, dass sich die Richtung wechselt.

2. Problem: Handbremse
Es hat mir einige Zeit gekostet die Handbremse zwischen AE und RMT synchron hin zu bekommen. War sie bei RMT aus, wurde sei noch unter AE als: "An" angezeigt.
Funktioniert RMT mit AE nicht oder muss AE deaktiviert werden?

3. Problem
Zwichenzeitlich funktioniert das Brems- und Gaspedal nicht mehr unter RMT.
Ich kann auf die Bremse treten und das Fahrzeug fährt trotzdem weiter.
Auch die Bremslichter gehen nicht an.

Mit freundlichen Grüßen

Martin Rupp

**Comment by modelleicher** [comment]
Moin..

Zuerst die Frage, was ist AE? Steh da etwas auf dem Schlauch. Enhanced Vehicle? VCA?

Generell gilt im LS eine Grundregel, und das ist, KEINE DOPPELBELEGUNGEN. 
Das hat Giants leider verbockt, da kommt man nicht drumherum. Es gibt ja zwei Spalten, "Taste 1" und "Taste 2" in den Menü-Einstellungen. In jeder Spalte darf jede Taste nur 1x für das selbe Fahrzeug vorkommen, sonst wird nur eine erkannt. 
Sprich wenn du die selbe Taste für die Handbremse in AE und RMT haben willst musst du einmal "Taste 1" belegen und einmal "Taste 2".
Außerdem gilt, doppelte Funktionen deaktivieren. 
Sprich Reverser, Handbremse etc. sofern RMT aktiv ist in einem Traktor dann von anderen Mods deaktivieren, sonst kann es zu Wechselwirkungen kommen. Da könnte auch dein 3. Problem mit zusammenhängen vielleicht.

LG

**Comment by RuppMartin001** [comment]
Hallo modelleicher,

ja, ich meinte TSX Enhanced Vehicle. 
Ich habe die Shuttle-Funktion von Enhanced Vehicle mit Strg + Leertaste für das Fahrzeug deaktiviert.
Dann gingen: Bremse und Gas wieder.

Die Tasten des Lenkrads habe ich nun in der zweite "Gamepad"-Spalte definiert.
Und tatsächlich kannt ich nun die Richtung und die Range-Sets über die Knöpfe des Lenkrads ändern.

Vielen Dank für die Tipps!

Ich habe leider noch ein Problem mit meinen Headtracking. Dazu mache ich aber einen anderen Issue auf.

Viele Grüße

Martin Rupp
