### ISSUE TITLE
problem V 0.5.1.1 mit TSX_EnhancedVehicle

### ISSUE THREAD

**Issue by Sirucool** [modelleicher/FS19_realManualTransmission#38]
seit der version 0.5.1.1 funktioniert die wendeschaltung von TSX_EnhancedVehicle nicht mehr .Das fahrzeug fährt bei deaktivierten RMT nur noch vorwärts . Bei der version 0.4.0.6 von RMT geht alles.
Das ist bei allen Fahrzeugen wo sich RMT einbaut.

**Comment by JohnDeere6920** [comment]
Jap. Hab das selbe Problem. Sobald ich die Wendeschaltung von EV auf ne andere taste lege wie die von RMT geht es. wäre aber schöner wenn es gehen würde.

**Comment by modelleicher** [comment]
@JohnDeere6920 da hast du ein anderes Problem. Und zwar das Problem der Doppelbelegung.. Da kann ich auch nix ändern, das ist ein Giants-Problem.
Man kann leider jede Taste nur 1x pro aktives Fahrzeug verwenden. 
Es gibt einen Trick, in der Tastenbelegung hat man ja zwei Spalten "Taste 1" und "Taste 2" jetzt ist es so dass jede Taste nur einmal in jeder Spalte pro aktives Fahrzeug vorkommen kann.
D.h. wenn du die Taste für EV z.b. in "Taste 1" Spalte legst und für RMT dann in "Taste 2" Spalte geht es.

Hat aber mit dem von Sirucool beschriebenen Bug nix zu tun denke ich ;) 

@Sirucool probier mal ob es mit der aktuellen Version für dich auch behoben ist. (V 0.5.1.2)

LG

**Comment by Sirucool** [comment]
@modelleicher kann erst am wochenende testen melde mich dann.

**Comment by JohnDeere6920** [comment]
Okay, Dann probiere ich das mal. Vielen dank für deine Mühen. 👍
