### ISSUE TITLE
DLC Class

### ISSUE THREAD

**Issue by fliper290** [modelleicher/FS19_realManualTransmission#49]
Good day

Will your gearbox support the latest DLC Class?

Thank you

**Comment by modelleicher** [comment]
Hello,
At some point, yes. 
I need to implement a way to add Configs do DLC's via basegameConfigs.xml first, and then there's the small issue of the Claas Tractors all having a combination of automatic and powershift transmissions, and there is no automatic in RMT yet.. So there is no way to accurately represent the Claas Transmissions yet anyways.

**Comment by seltNik** [comment]
When will that be possible?

**Comment by seltNik** [comment]
Wann wird das möglich sein?
