### ISSUE TITLE
HUD / RangeSet Frage

### ISSUE THREAD

**Issue by WiboVanWijk** [modelleicher/FS19_realManualTransmission#5]
Moinsen, 

ich habe mir ja das Getriebe für den ZT 320 zusammen "gebastelt". Das Getriebe hat 4 Gänge, 3 Gruppen    vorwärts, 2 Gruppen rückwärts sowie eine sogenannte ULS (Unterlaststufe). 

Die Gruppen für vorwärts/rückwärts liegen im RangeSet1 und die ULS im RangeSet2. Im HUD wird mir RangeSet1 angezeigt.  Die ULS lässt sich aktivieren, wird aber nicht im HUD angezeigt,das sie aktiviert ist. 

Fehler meiner seits?

Besteht die möglichkeit, Rangeset2 für einzelne range (Gruppe) in RangeSet1 zusperren ?

Ich versuche nämlich das umzusetzen. Die ULS soll nur in der Gruppe 1 , 2 (vorwärts)  sowie den beiden Gruppen rückwärts einsetzbar sein.

MfG
Wibo

**Comment by modelleicher** [comment]
Moin,

Die verschiedenen Rangesets sollten eigentlich alle bei Range: hintereinander angezeigt werden..  Muss ich mal schauen vielleicht hat sich da ein Bug eingeschlichen :)

Derzeit gibt es keine Möglichkeit einzelne Gruppen von anderen Gruppensets aus zu sperren. Ist aber etwas das ich noch einbauen möchte, ich weiß nur noch nicht wie am besten umsetzen.
Was passiert jetzt z.b. wenn ich in der ULS in RangeSet2 bin und in RangeSet1 in eine andere Gruppe schalte. Entweder muss ich dann das schalten in dieses Rangeset sperren, oder aber beim schalten in dieses Rangeset wird man im anderen Rangeset quasi aus der Gruppe geworfen.

Derzeit ist ja disableInRangeSetX bei den Gears, dass man einzelne Gänge in entsprechenden Gruppen deaktivieren kann. Das funkioniert aber auch noch nicht so 100% weil das selbe Problem herrscht.. Was sperrt jetzt wen. ;)

LG

**Comment by modelleicher** [comment]
So, hab das mit den gesperrten Ranges/Gears noch mal überarbeitet in der aktuellen Version, probier mal ob du damit jetzt das Getriebe so aufbauen kannst wie in echt :) 

Der Bug dass im Hud nur RangeSet1 angezeigt wurde ist auch gefixt :) 

LG

**Comment by WiboVanWijk** [comment]
Hallo, HUD funktioniert. Die ULS lässt sich jetzt nicht mehr in der der Gruppe 3 aktivieren. Sie bleibt zwar wenn ich von der Gruppe 2 + ULS in die 3 schalte aktiviert. Damit kann ich aber sehr gut leben. Was würden wir nur ohne euch Modder machen.

Du hast aber ein kleinen Fehler in der basegameConfigs.xml es wird dieser Error ausgeworfen: 

C:/Users/sysea/Documents/MyGames/FarmingSimulator2019/mods/FS19_realManualTransmission/basgameConfigs.xml. ="1" name="IV" > ausgeworfen.

In Zeile 35 fehlt das range ;)

LG

**Comment by modelleicher** [comment]
Hmm.. kannst du vielleicht mal die Config posten dass ich sehe was du genau vor hast und was noch anders werden müsste dass es passt? 

Ups.. Oh.. Also gleich noch ein Hotfix für die XML xD

LG

**Comment by WiboVanWijk** [comment]
Na Klar

```
<realManualTransmission>		
	<gears>
            <gear speed="8.07" name="1" />
            <gear speed="13.89" name="2" />
            <gear speed="22.15" name="3" />
            <gear speed="35" name="4" />
        </gears>	 
	<!-- RangeSets-->
	<rangeSet1 powerShift="false" defaultRange="3" hasNeutralPosition="false" >
            <range ratio="0.333" name="RII" isReverse="true" />
            <range ratio="0.2675" name="RI" isReverse="true" />
            <range ratio="0.259" name="I" />
            <range ratio="0.322" name="II" />
            <range ratio="1" name="III" >
                 <disableRangesSet2 ranges="1" disableType="lock" /> 
	    </range>
	</rangeSet1>

       <rangeSet2 powerShift="false" defaultRange="2" >
            <range ratio="0.71" name="ULS" />
            <range ratio="1" name="VLS" />
        </rangeSet2>
</realManualTransmission>
```
Es kann natürlich sein, das im Wirklichkeit die ULS vor dem wechsel in die III herausgenommen werden muss und nicht sowie ich mir das denke automatisch in die VLS gewechselt wird. Das geben leider meine technischen Daten (Test von 1985) nicht preis.

**Comment by modelleicher** [comment]
Ich vermute dass man in echt vielleicht einfach nicht in Gruppe 3 schalten kann sobald die ULS aktiviert ist. Muss mir das noch mal im Code anschauen, eigentlich sollte es schon so funktionieren.. :D 

LG

**Comment by modelleicher** [comment]
So, aktuelle Version sollte es jetzt alles richtig sein :)

**Comment by WiboVanWijk** [comment]
Guten Morgen, funzt Danke !

Ich wollte es gestern Abend testen (muss immer bis 21.30 arbeiten), habe mich aber entschieden dein Live-Replay zuschauen. :) Die Marwell Manor Farm von: Oxygendavid ist ne schöne Map, ab Farm-Manager kann mann sein Hof selbst gestallten. Aber Links verkehr.

Grafik/FPS Einbrüche: Ich habe auch eine GTX1070, habe deine Probleme nicht so extrem. Hatte auch mal die Anleitung aus dem Gaints Forum ausprobiert. Hat alles noch schlimmer gemacht, wo ich vorher 60 FPS hatte waren es damit nur noch 40 und weniger.

LG
