### ISSUE TITLE
Lastschaltbare Gänge

### ISSUE THREAD

**Issue by Zutroy87** [modelleicher/FS19_realManualTransmission#50]
Halllo Modelleicher,

Zuerst einmal vielen Dank für deine tolle Arbeit.
Gibt es eine Möglichkeit die Gänge statt den Fahrstufen in der xml  lastschaltbar  zu machen?
Bei den Fahrstufen geht es ja, ich bräuchte aber lastschaltbare Gänge.
Gruß,

Philipp

**Comment by modelleicher** [comment]
Hallo,
powerShift="true" funktioniert auch bei den Gängen ;)

**Comment by Zutroy87** [comment]
Hallo,

Danke, hat funktioniert!

Gruß
