### ISSUE TITLE
Added Realism For Vehicles

### ISSUE THREAD

**Issue by Kynuska** [modelleicher/FS19_realManualTransmission#51]
Hello. I suppose these two modes will not be compatible. It would be great if they could both be together.
https://farming-simulator.com/mod.php?lang=en&country=cz&mod_id=138280&title=fs2019

**Comment by D9005** [comment]
Hi,
if you open the REA.lua and change line 48 from: 
"VehicleMotor.updateGear = REA.REAupdateGear;"
to:
"--VehicleMotor.updateGear = REA.REAupdateGear;"
the gearbox of the other mod is disabled.
That works well for me now with RMT.
I hope i could help.

Kind regards D9005

**Comment by Kynuska** [comment]
thank you very much.

**Comment by D9005** [comment]
No problem 😉
