### ISSUE TITLE
Problem: Running LUA method 'update'/'draw'

### ISSUE THREAD

**Issue by Ravenor712** [modelleicher/FS19_realManualTransmission#54]
Moin!

Habe mit deinem RMT schon den verschiedene Getriebe im John Deere 6M und 6R eingebaut und dort funktioniert es ohne Problem.

Nur bei diesem Mod [https://www.farming-simulator.com/mod.php?lang=de&country=de&mod_id=141860&title=fs2019](url) habe ich Probleme. Jedes mal wenn ich versuche eine **Gruppe zu implementieren** bekomme ich Fehlermeldungen im Log sowie keine HUD-Anzeige mehr im FS19 (Siehe Anhang)...

Gibt es hierfür eine Lösung oder ist der Mod dafür nicht geeignet?

![Fehler](https://user-images.githubusercontent.com/40805078/69827854-88fd3780-1219-11ea-8dc9-b949a2461ea2.png)
![series7R](https://user-images.githubusercontent.com/40805078/69827858-8dc1eb80-1219-11ea-90eb-1293e26f325f.png)
[log.txt](https://github.com/modelleicher/FS19_realManualTransmission/files/3902834/log.txt)

**Comment by Ravenor712** [comment]
Lösung gefunden:

Zeile 77-> defaultRange "B" geändert auf defaultRange "1", Gruppenbuchstabe wird von RMT nicht erkannt sondern nur die Zahlenreihenfolge: Gruppe A-> "1" Gruppe B-> "2"

**Comment by modelleicher** [comment]
Jup defaultRange bezieht sich auf den Index der Gruppe, nicht den Namen ;)
