### ISSUE TITLE
V 0.4.0.5 undefined gear error

### ISSUE THREAD

**Issue by ivanlii** [modelleicher/FS19_realManualTransmission#6]
Hi, just testing FIAT, 4 gears. If by mistake enter gear 5 (g27 shifter):
_2019-02-07 21:55 Error: Running LUA method 'update'.
2019-02-07 21:55 C:/Users/Lii/Documents/My Games/FarmingSimulator2019/mods/FS19_realManualTransmission/realManualTransmission.lua:1138: bad argument #1 to 'min' (number expected, got nil)_

PS: short test with FS19_VehicleControlAddon (disabled gears and shuttle in vehicleControlAddonConfig.xml)
 and TSX_EnhancedVehicle (disabled shuttle in TSX_EnhancedVehicle.xml), and all seems ok for now. This is great, thank you.

**Comment by modelleicher** [comment]
Should be fixed with V 0.4.0.6 :)
