### ISSUE TITLE
Multiplayer - Motor geht nach dem Einlegen des Ganges aus (Habe Pedal für Kupplung)

### ISSUE THREAD

**Issue by RuppMartin001** [modelleicher/FS19_realManualTransmission#68]
Hallo Modelleicher,

ich habe leider noch Probleme mit der Version 0.6.0.4 im Multiplayer-Modus.
Sobald sich ein zweiter Spieler anmeldet geht der Motor aus, sobald ich einen Gang einlege, obwohl die Kupplung betätigt ist.
Ich habe ein Kupplungspedal. Clutch geht auch auf 0 %, wenn ich das Kupplungspedal betätige.

Wenn der Gang schon vor dem Anlassen eingelegt ist, ich die Kupplung betätige und dann den Motor anlasse, geht er gleich wieder aus.

Lasse ich den Gang in Leerlaufstellung und starte den Motor, geht die Drehzahl von 850 U/min auf 1724 U/min beim Valtra N 174.

Viele Grüße

Martin

**Comment by modelleicher** [comment]
Sollte in der aktuellen Version 0.6.0.6 gefixt sein :)

**Comment by RuppMartin001** [comment]
Hallo modelleicher,

Ich habe es ausprobiert. Das Problem ist behoben.

Vielen Dank für die Behebung

Viele Grüße

Martin
