### ISSUE TITLE
Bremse bremst nicht richtig

### ISSUE THREAD

**Issue by beowulf99x** [modelleicher/FS19_realManualTransmission#7]
Hi, vielleicht ein Fehler von mir, aber wenn ich anhalte rollt das Fahrzeug weiter. Besonders extrem wenn ich rückwärts fahre und anhalten will. 
Egal welcher Gang, auch "N" oder Gruppe, bei allen so. Auch beim Kupplung treten/loslassen
Mach ich da was Falsch?

Habe das G27 + Saitek Side Panel

Bei mir speichert er den HUD nicht wenn ich diesen an eine gewünschte Position schiebe.
Kann ich auch die Schrifgröße irgendwo etwas verklinern?

VG+ Danke für diesen Mod

**Comment by modelleicher** [comment]
Hi,

Also der Mod bremst nicht automatisch wie Giants, sprich wenn du nicht selbst bremst rollt der Schlepper weiter. Aber ich nehme an dass du meinst dass du das Bremspedal betätigst und es keine Wirkung hat? 

Funktioniert die Handbremse denn? 

Da Gas und Bremse an sich auf der selben Achse liegen im LS könnte es sein dass dein Gaspedal immer minimal gas gibt (Deadzone?) und daher die Bremse nicht anspricht.
Ansonsten, am besten mal mit Log posten oder ein kurzes Video vom Problem (mit gsVehicleDebugPhyiscs aktiv) oder genauer beschreiben, dass ich es reproduzieren kann :) 

Die Schriftgröße ist im Moment statisch, mal schauen ob ich da noch ein Setting oder so was für einbauen kann :) 
Wegen speichern des Huds schaue ich selbst gleich noch mal nach bei mir ob alles geht.. Wenn ja dann brauch ich auch da weitere Infos :) 

LG

**Comment by beowulf99x** [comment]
Genau, ich meine das das Bremspedal keine Wirkung hat bei "stillstand" im Vorwärtsgang. Wenn ich rückwärts fahre, kann ich kurz abbremsen, danach rollt er weiter (je nach Geschwindigkeit)

Das hab ich erst seit deinem Mod so...

Habe es auch herausgefunden was das Problem war (jedenfalls teilweise):
Es lag am TSX_EnhancedVehicle Mod.
Hatte neuen Modordner erstellt und nur ein paar für mich "wichtige" mit reingepackt. Und beim TSX_EnhancedVehicle Mod trat das Problem auf.
Im Anhang die xml-Datei aus meinem modsSettings Ordner
[TSX_EnhancedVehicle_v1.zip](https://github.com/modelleicher/FS19_realManualTransmission/files/2847014/TSX_EnhancedVehicle_v1.zip)

Eventuell hilft es den Fehler zu finden.
VG

**Comment by modelleicher** [comment]
Hallo,

Ich spiele selbst mit TSX (die letzte Version von Github) bei mir geht es / reicht es das Shuttle auszuschalten bei den Fahrzeugen die RMT verbaut haben.
Somit kann ich weiterhin das TSX Shuttle verwenden in den Fahrzeugen die kein RMT verbaut haben bzw. CVT sind :) 

LG

**Comment by beowulf99x** [comment]
Danke, teste ich mal :)
