### ISSUE TITLE
Dedi-Server

### ISSUE THREAD

**Issue by gamegirl312** [modelleicher/FS19_realManualTransmission#74]
Hi ich habe gehört das es wohl auch auf einem Server funktioniert. Ich hab nur ein Problem damit Mod Fahrzeuge mit der Funktion hinzuzufügen... Generell funktioniert es mit den Fahrzeugen die Sie konfiguriert haben, aber wenn ich es in einen Mod hinzufüge und diesen dann auf den Server hochlade funktioniert es dort nicht. Habe das ganze auch im Solo- und Multiplayerspiel versucht dort funktioniert es einwandfrei... Da ich aber mit meinen Freunden auf einem Server spiele, weil wir nicht immer alle zur selben Zeit online sind wollte ich es dort einfügen.
Können Sie mir vielleicht sagen warum es nicht klappt wenn ich die geänderten Mods auf den Server lade? Wie gesagt außerhalb des Servers funktioniert es ohne Probleme.

Hoffe Sie können mir da weiterhelfen, weil es echt eine super Sache ist, wenn die bearbeiteten Mods dann noch auf dem Server funktionieren ist es mehr als nur genial.

**Comment by modelleicher** [comment]
Was genau meinst du mit "es funktioniert nicht auf dem Server" lassen sich die Mods nicht hochladen? Nicht aktivieren? Wo liegt das Problem?

LG

**Comment by gamegirl312** [comment]
Die Mods generell funktionieren aber ohne den RMT. 

Aber ich glaube ich habe grade meinen Fehler gefunden. Da es sich hierbei um Mods handelt die aus dem InGame Modhub sind wird mir beim hochladen auf den Server angezeigt das es ein Update für diese Mods gibt, da ich diese immer automatisch mache und nicht drauf achte um welche Mods es sich handelt bzw. da ich dies bei fast allen Mods angezeigt bekomme die ich auf den Server lade ist es ja logisch das es nicht funktioniert... so wird ja die originale Datei wieder geladen......... hab es grade nach mehrerem hin und her dann endlich geschafft das die Mods damit laufen :D 

Auweia ich sollte vielleicht mal anfangen nicht immer alles so schnell zu machen :D mir passieren ständig solche kleinen Fehler da ich einfach zu schnell klicke XD

Trotzdem danke für die schnelle Antwort :D falls mal ein wirkliches Problem vorliegt (und nicht so ein dummer eigener Fehler XD) werde ich mich wieder hier melden.

LG
