### ISSUE TITLE
Leistungsverlust durch GPS (Spurführung)

### ISSUE THREAD

**Issue by Einfllslos** [modelleicher/FS19_realManualTransmission#75]
Hallo, ich habe festgestellt dass die Traktoren Leistung verlieren, sobald ich die Spurführung  (von Wopster) aktiviere. 
Also nicht das Aktivieren vom Mod an sich ist das Problem, sondern das Aktivieren der Spurführung ingame. Sobald man diese einschaltet verliert der Traktor an Leistung (getestet mit Fiat1300DT von dir und Claas Arion 460) 
Allerdings gibt es einen Trick bei der Sache, nämlich Handgas benutzen. Mit Handgas hat der Traktor wieder die normale Leistung, nur Fußgas (in meinem Fall weil ich Lenkrad und Pedale hab) und bei dem tempomat verreckt der Schlepper förmlich.
Ich kann natürlich jetzt nicht sagen, ob der Fehler bei RMT oder GPS liegt, nur fand ich das mit dem Handgas konisch, deswegen wollte ich es mal posten. Du kannst ja zuerst mal schauen, ob sich der Fehler reproduzieren lässt.
Schöne Grüße

**Comment by BlackscreenHD** [comment]
Das ist mir ebenfalls schon exakt so aufgefallen.

**Comment by modelleicher** [comment]
Hmm, eigentlich sollte GPS ja nur lenken und kein Tempomat sein, oder wie ist das?
Klingt als würde GPS als Tempomat agieren und das Gaspedal limitieren.

LG

**Comment by Einfllslos** [comment]
Ja, das könnte schon sein, dass es da das Gaspedal limitiert. 
Ich hätte auch gesagt, dass es nur lenken soll, aber was mir gerade auffällt da war auch noch etwas komisch mit dem Rückwärtsfahren bei aktivierter Spurführung. Muss ich allerdings nochmal nachschauen.

**Comment by Einfllslos** [comment]
Hallo, mir ist eben noch etwas aufgefallen. 
Wenn man die Spurführung aktiviert hat und steht dann kann man auch kein Gas geben (Ausnahme wieder Handgas).
Hab es probiert mir Gang drin und ausgekuppelt oder auch Leerlauf spielt da keine Rolle. Sehr komisch das alles.

**Comment by modelleicher** [comment]
hmm.. 
Ja ich hab selbst noch nie mit GPS gespielt die Fahrzeuge die ich so fahre haben alle keins^^
Aber da muss ich wohl mal schauen wo da der Konflikt liegt..
