### ISSUE TITLE
Question about JD AutoPowerShift

### ISSUE THREAD

**Issue by DrewCZ** [modelleicher/FS19_realManualTransmission#76]
Hello modelleicher! 
thank you for your mod. I have one question: how to set up (if possible?) gearbox JD AutoPowerShift? This is 16F+4R powershift gearbox, no ranges. 
But - if I have correct infos - is possible allow gearbox to switch gear automatically, depends on engine load. 
Is there any way (in combination of ranges? swap? I don't know) how to set up similar function? Of course permanently, not on demand.
Thank you. Ticho aka DrewCZ

**Comment by modelleicher** [comment]
Hello,
It is not possible to have RMT shift automatically.. I will include this feature eventually but its a lot of work/code if it's supposed to work right..

**Comment by DrewCZ** [comment]
Well, no "on demand" function mounted in gearbox at this moment :-)
Thank you for reply. Love your mod!
ticho
