### ISSUE TITLE
Maizeplus  Problem 

### ISSUE THREAD

**Issue by Kruemel241** [modelleicher/FS19_realManualTransmission#77]
ich hätte eine frage zum Maizeplus mod wenn ich diesen auf meiner karte hinzufüge und diese starte verschwinden immer alle Verkaufsstellen an denen man Silage verkaufen kann

Was kann ich dagegen tun?

Danke schon mal im voraus

**Comment by modelleicher** [comment]
Frage.. was hat das mit RMT zu tun? ;) 

Aber um deine Frage zu beantworten das ist ein Bug der ersten Version wenn CCM-Extension nicht aktiv ist. Entweder mit CCM-Extension spielen oder auf das Update warten das demnächst kommt ;) 
LG

**Comment by Kruemel241** [comment]
tut mir leid es hat nichts damit zu tun aber ich wusste nicht an wen ich mich wenden soll
trotzdem danke fürs beantworten 

ps: ich find deinen Videos echt gut vor allem Holzer map

**Comment by Einfllslos** [comment]
Ich würde mir da vielleicht Discord (Handy oder pc) holen, da kann man solche Sachen immer ganz gut Fragen und bekommt auch oft Support von anderen Spielern. ;)
