### ISSUE TITLE
- Feature Request - "Schlupf"

### ISSUE THREAD

**Issue by Lasergott** [modelleicher/FS19_realManualTransmission#8]
Hey,
vorab: Richtig guter Ersatz für das Gearbox Addon

Ich würde mir persönlich noch das Schlupf Feature wünschen. (Räder drehen durch -> Grasnabe reist auf ->  Dann bringt der Striegel mit Saatfunktion auch was :D)

Lg

**Comment by modelleicher** [comment]
Dafür müsste man die Räder erst mal zum durchdrehen bringen, was bisschen schwierig ist mit doppelten Traktionswerten.. Bin mir aber nicht sicher ob das in diesem Mod gefixt werden sollte.

LG
