### ISSUE TITLE
Question regarding <ratedRpm=" "/>

### ISSUE THREAD

**Issue by mrPassion78** [modelleicher/FS19_realManualTransmission#82]
Hi` there modeleicher, 
i have tried to implement the ratedRpm, sins this is very helpfull for all realism in the gearbox, but i`m getting an error when i enter it like in this gearbox>> **(its near the bottom)**this is for the
John Deere 6145/55R

> 
<realManualTransmissionConfiguration name="6145/55R 8*3" price="0" >	

	<realManualTransmission  autoRangeMatching="true">	
				<gears defaultGear="4" powerShift="false" >						
					<gear speed="14.8" name="1" speedMatchingPercentageUp="0.54" speedMatchingPercentageDown="0.11"/>
					<gear speed="17.9" name="2" speedMatchingPercentageUp="0.48" speedMatchingPercentageDown="0.16" />
					<gear speed="22.0" name="3" speedMatchingPercentageUp="0.41" speedMatchingPercentageDown="0.22"/>
					<gear speed="26.7" name="4" speedMatchingPercentageUp="0.34" speedMatchingPercentageDown="0.28" />
					<gear speed="32.7" name="5" speedMatchingPercentageUp="0.28" speedMatchingPercentageDown="0.34"/>
					<gear speed="39.6" name="6" speedMatchingPercentageUp="0.22" speedMatchingPercentageDown="0.41" />
					<gear speed="48.4" name="7" speedMatchingPercentageUp="0.16" speedMatchingPercentageDown="0.48" />
					<gear speed="53.0" name="8" speedMatchingPercentageUp="0.11" speedMatchingPercentageDown="0.54" />					
				</gears>
				<rangeSet1 defaultRange="2" powerShift="true" >
					<range ratio="0.183" name="A"  />
					<range ratio="0.364" name="B" />
					<range ratio="1.000" name="C"  />				
				</rangeSet1>
		<reverser type="normal"> 
			<ratios forward="1" reverse="0.566" />
			<settings brakeAggressionBias="0.1" clutchTime="600" />
		</reverser>	
		<fluidClutch stallRpm="540" /> 
               <ratedRpm="2100" />
	</realManualTransmission>
	</realManualTransmissionConfiguration>

Than it will say that after the "2100"/> the is no store data available , and the mod is "dumped" .
Where should be the correct place to enter this to get it to work?

Thnx in advance, and keep up the awesome gearbox mod..

Greetings Pascal

**Comment by modelleicher** [comment]
ratedRpm is placed in this line like this <realManualTransmission ratedRpm="2100" autoRangeMatching="true">

**Comment by mrPassion78** [comment]
> ratedRpm is placed in this line like this

thnx for the reply, but the answer is missing text?

**Comment by modelleicher** [comment]
Sry I always forget that Github can't have code in plain text
`
<realManualTransmission ratedRpm="2100" autoRangeMatching="true">
`
