### ISSUE TITLE
Reverser Callstack

### ISSUE THREAD

**Issue by CityFarmerDE** [modelleicher/FS19_realManualTransmission#84]
Hallo,

die v.0.6.0.8 hat bei mir Callstacks und der Reverser funktioniert nicht. 

UIP_SYNCH_REVERSER - reverser not nil
2020-06-02 19:13 Error: Running LUA method 'update'.
2020-06-02 19:13 F:/Mods/FS19_realManualTransmission/rmtReverser.lua:45: attempt to index global 'rev' (a nil value)

[log.txt](https://github.com/modelleicher/FS19_realManualTransmission/files/4718725/log.txt)

**Comment by modelleicher** [comment]
Sollte mit 0.6.0.9 gefixt sein hoffe ich :)

**Comment by CityFarmerDE** [comment]
Hallo,

der Reverser funktioniert beim mir jetzt wieder problemlos. Konnte allerdings nur im SP testen.
Hast du auch etwas an der Kupplung gemacht? Ich hatte das Gefühl, die funktioniert  besser als in 0.6.0.7

Danke für deine Mühe
