### ISSUE TITLE
Reverser never working

### ISSUE THREAD

**Issue by JNAUS23** [modelleicher/FS19_realManualTransmission#85]
Hallo Modelleicher,

ich finde den Mod echt toll, nur habe ich ein Problem.
Ich kann nicht rückwärts fahren! Gar nicht. Wenn ich versuche, den Reverser über eine 
vorher festgelegte Taste zu aktivieren, passiert gar nichts, auch wenn der Reverser vorhanden ist.
Und selbst wenn ich in einen Rückwärtsgang schalte, welcher laut xml auch Rückwärts ist, fahre ich mit diesem trotzdem vorwärts. Woran könnte das liegen? An eventuellen anderen Mods? 
Über eine Antwort würde ich mich sehr freuen.

Grüße
"JJX S5"

**Comment by CityFarmerDE** [comment]
Die aktuelle Version hat ein Problem mit dem Reverser. Benutze Version 0.6.0.7, da sollte es funktionieren.

MfG

**Comment by JNAUS23** [comment]
wie kann man sich eine ältere Version runterladen?

Lg

**Comment by CityFarmerDE** [comment]
commits --> Version auswählen --> browse files --> Zip downloaden

Hoffe das hilft

MfG

**Comment by astro80** [comment]
same problem for me

**Comment by modelleicher** [comment]
Should be fixed now :) Please report back if it works

**Comment by JNAUS23** [comment]
I will try the current version in a  few days, currently not home, gonna report if it works soon :) Mfg und danke dir!

**Comment by astro80** [comment]
works for me!
