### ISSUE TITLE
Speed Matching/autorange matching

### ISSUE THREAD

**Issue by Sozzy76** [modelleicher/FS19_realManualTransmission#88]
Hi, Modelleicher, 

I'm looking for some help I cant seem to get the speed matching to work, I've tried everything I can get it to work

I have attached a modded JCB, can you tell me what I need to change to allow the speed matching to work on all gears
[FBM19_Fasttrac4220.zip](https://github.com/modelleicher/FS19_realManualTransmission/files/4845596/FBM19_Fasttrac4220.zip)

regarding Auto Range Matching, can you send me a example

**Comment by modelleicher** [comment]
Hi,
In Order for auto-range-matching to work you need ranges.. You don't have any ranges in your Fastrac.
